import mongoose from "mongoose";
import Book from "../models/book_model.js";
import { config } from "dotenv";

config();

const books = [
  {
    title: "Chạng Vạng",
    author: ["Stephenie Meyer"],
    description: "Câu chuyện tình yêu giữa người và ma cà rồng.",
    category: "Tiểu thuyết",
    price: 120000,
    publisher: "NXB Trẻ",
    publishDate: new Date("2005-10-05"),
    language: "Tiếng Việt",
    pages: 498,
    stock: 30,
    coverImageUrl: "/covers/chang-vang.jpg",
    imageUrls: ["/images/chang-vang-1.jpg"],
  },
  {
    title: "Harry Potter và Hòn Đá Phù Thủy",
    author: ["J.K. Rowling"],
    description: "Hành trình phiêu lưu của Harry Potter tại Hogwarts.",
    category: "Tiểu thuyết",
    price: 100000,
    publisher: "NXB Trẻ",
    publishDate: new Date("1997-06-26"),
    language: "Tiếng Việt",
    pages: 350,
    stock: 40,
    coverImageUrl: "/covers/harry-potter-1.jpg",
    imageUrls: ["/images/harry-potter-1-1.jpg"],
  },
  {
    title: "One Piece Tập 1",
    author: ["Eiichiro Oda"],
    description: "Hành trình trở thành Vua Hải Tặc của Luffy.",
    category: "Truyện tranh",
    price: 30000,
    publisher: "Kim Đồng",
    publishDate: new Date("1997-07-22"),
    language: "Tiếng Việt",
    pages: 200,
    stock: 50,
    coverImageUrl: "/covers/one-piece-1.jpg",
    imageUrls: ["/images/one-piece-1.jpg"],
  },
  {
    title: "Naruto Tập 1",
    author: ["Masashi Kishimoto"],
    description: "Chặng đường trở thành Hokage của Naruto Uzumaki.",
    category: "Truyện tranh",
    price: 30000,
    publisher: "Kim Đồng",
    publishDate: new Date("1999-09-21"),
    language: "Tiếng Việt",
    pages: 200,
    stock: 45,
    coverImageUrl: "/covers/naruto-1.jpg",
    imageUrls: ["/images/naruto-1.jpg"],
  },
  {
    title: "IT",
    author: ["Stephen King"],
    description: "Chú hề ma quái Pennywise gieo rắc nỗi sợ.",
    category: "Truyện kinh dị",
    price: 150000,
    publisher: "NXB Văn Học",
    publishDate: new Date("1986-09-15"),
    language: "Tiếng Việt",
    pages: 1138,
    stock: 20,
    coverImageUrl: "/covers/it.jpg",
    imageUrls: ["/images/it.jpg"],
  },
  {
    title: "The Shining",
    author: ["Stephen King"],
    description: "Khách sạn ma ám cùng những hiện tượng rùng rợn.",
    category: "Truyện kinh dị",
    price: 130000,
    publisher: "NXB Văn Học",
    publishDate: new Date("1977-01-28"),
    language: "Tiếng Việt",
    pages: 450,
    stock: 15,
    coverImageUrl: "/covers/the-shining.jpg",
    imageUrls: ["/images/the-shining.jpg"],
  },
  {
    title: "Đắc Nhân Tâm",
    author: ["Dale Carnegie"],
    description: "Nghệ thuật giao tiếp và thuyết phục trong cuộc sống.",
    category: "Sách truyền cảm hứng",
    price: 90000,
    publisher: "NXB Tổng Hợp TP.HCM",
    publishDate: new Date("1936-01-01"),
    language: "Tiếng Việt",
    pages: 320,
    stock: 40,
    coverImageUrl: "/covers/dac-nhan-tam.jpg",
    imageUrls: ["/images/dac-nhan-tam.jpg"],
  },
  {
    title: "Quẳng Gánh Lo Đi Và Vui Sống",
    author: ["Dale Carnegie"],
    description: "Hướng dẫn cách giảm lo âu để sống hạnh phúc.",
    category: "Sách truyền cảm hứng",
    price: 85000,
    publisher: "NXB Lao Động",
    publishDate: new Date("1948-01-01"),
    language: "Tiếng Việt",
    pages: 300,
    stock: 30,
    coverImageUrl: "/covers/quang-ganh-lo.jpg",
    imageUrls: ["/images/quang-ganh-lo.jpg"],
  },
  {
    title: "Sapiens: Lược Sử Loài Người",
    author: ["Yuval Noah Harari"],
    description: "Tổng quan lịch sử phát triển của nhân loại.",
    category: "Sách bổ sung kiến thức",
    price: 180000,
    publisher: "NXB Dân Trí",
    publishDate: new Date("2011-01-01"),
    language: "Tiếng Việt",
    pages: 500,
    stock: 25,
    coverImageUrl: "/covers/sapiens.jpg",
    imageUrls: ["/images/sapiens.jpg"],
  },
  {
    title: "Lược Sử Thời Gian",
    author: ["Stephen Hawking"],
    description: "Vũ trụ, thời gian và những điều chưa biết.",
    category: "Sách bổ sung kiến thức",
    price: 120000,
    publisher: "NXB Trẻ",
    publishDate: new Date("1988-04-01"),
    language: "Tiếng Việt",
    pages: 250,
    stock: 20,
    coverImageUrl: "/covers/brief-history-of-time.jpg",
    imageUrls: ["/images/brief-history.jpg"],
  },
  {
    title: "Attack on Titan Tập 1",
    author: ["Hajime Isayama"],
    description: "Cuộc chiến chống lại Titan của nhân loại.",
    category: "Truyện tranh",
    price: 35000,
    publisher: "Kim Đồng",
    publishDate: new Date("2009-09-09"),
    language: "Tiếng Việt",
    pages: 190,
    stock: 60,
    coverImageUrl: "/covers/aot-1.jpg",
    imageUrls: ["/images/aot-1.jpg"],
  },
  {
    title: "Conan Tập 1",
    author: ["Gosho Aoyama"],
    description: "Thám tử nhí Conan phá các vụ án ly kỳ.",
    category: "Truyện tranh",
    price: 30000,
    publisher: "Kim Đồng",
    publishDate: new Date("1994-01-05"),
    language: "Tiếng Việt",
    pages: 180,
    stock: 55,
    coverImageUrl: "/covers/conan-1.jpg",
    imageUrls: ["/images/conan-1.jpg"],
  },
  {
    title: "Pet Sematary",
    author: ["Stephen King"],
    description: "Nghĩa địa ma quái khiến người chết sống lại.",
    category: "Truyện kinh dị",
    price: 140000,
    publisher: "NXB Văn Học",
    publishDate: new Date("1983-11-14"),
    language: "Tiếng Việt",
    pages: 400,
    stock: 18,
    coverImageUrl: "/covers/pet-sematary.jpg",
    imageUrls: ["/images/pet-sematary.jpg"],
  },
  {
    title: "Think and Grow Rich",
    author: ["Napoleon Hill"],
    description: "Tư duy làm giàu và phát triển bản thân.",
    category: "Sách truyền cảm hứng",
    price: 95000,
    publisher: "NXB Lao Động",
    publishDate: new Date("1937-01-01"),
    language: "Tiếng Việt",
    pages: 300,
    stock: 35,
    coverImageUrl: "/covers/think-and-grow-rich.jpg",
    imageUrls: ["/images/think-and-grow-rich.jpg"],
  },
  {
    title: "21 bài học cho thế kỷ 21",
    author: ["Yuval Noah Harari"],
    description: "Những thách thức và cơ hội của thế giới hiện đại.",
    category: "Sách bổ sung kiến thức",
    price: 150000,
    publisher: "NXB Dân Trí",
    publishDate: new Date("2018-08-30"),
    language: "Tiếng Việt",
    pages: 400,
    stock: 25,
    coverImageUrl: "/covers/21-lessons.jpg",
    imageUrls: ["/images/21-lessons.jpg"],
  },
  {
    title: "Sherlock Holmes: Tập 1",
    author: ["Arthur Conan Doyle"],
    description: "Những vụ án ly kỳ của thám tử Sherlock Holmes.",
    category: "Tiểu thuyết",
    price: 80000,
    publisher: "NXB Văn Học",
    publishDate: new Date("1887-03-01"),
    language: "Tiếng Việt",
    pages: 320,
    stock: 30,
    coverImageUrl: "/covers/sherlock-1.jpg",
    imageUrls: ["/images/sherlock-1.jpg"],
  },
  {
    title: "Death Note Tập 1",
    author: ["Tsugumi Ohba", "Takeshi Obata"],
    description: "Quyển sổ tử thần thay đổi thế giới.",
    category: "Truyện tranh",
    price: 35000,
    publisher: "Kim Đồng",
    publishDate: new Date("2003-12-01"),
    language: "Tiếng Việt",
    pages: 190,
    stock: 60,
    coverImageUrl: "/covers/death-note-1.jpg",
    imageUrls: ["/images/death-note-1.jpg"],
  },
  {
    title: "Dracula",
    author: ["Bram Stoker"],
    description: "Câu chuyện kinh dị về ma cà rồng Dracula.",
    category: "Truyện kinh dị",
    price: 100000,
    publisher: "NXB Văn Học",
    publishDate: new Date("1897-05-26"),
    language: "Tiếng Việt",
    pages: 400,
    stock: 20,
    coverImageUrl: "/covers/dracula.jpg",
    imageUrls: ["/images/dracula.jpg"],
  },
  {
    title: "Nhà Giả Kim",
    author: ["Paulo Coelho"],
    description: "Hành trình khám phá bản thân và số mệnh.",
    category: "Sách truyền cảm hứng",
    price: 90000,
    publisher: "NXB Hội Nhà Văn",
    publishDate: new Date("1988-01-01"),
    language: "Tiếng Việt",
    pages: 250,
    stock: 30,
    coverImageUrl: "/covers/nha-gia-kim.jpg",
    imageUrls: ["/images/nha-gia-kim.jpg"],
  },
  {
    title: "Kiến Thức Tổng Hợp Về Khoa Học",
    author: ["National Geographic"],
    description:
      "Cuốn sách tổng hợp những kiến thức thú vị về thế giới tự nhiên, con người và vũ trụ.",
    category: "Sách bổ sung kiến thức",
    price: 160000,
    publisher: "NXB Kim Đồng",
    publishDate: new Date("2015-09-01"),
    language: "Tiếng Việt",
    pages: 350,
    stock: 25,
    coverImageUrl: "/covers/kien-thuc-tong-hop.jpg",
    imageUrls: ["/images/kien-thuc-tong-hop.jpg"],
  },
];

const seedBooks = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    await Book.deleteMany({});
    await Book.insertMany(books);
    console.log("Books seeded successfully!");
  } catch (error) {
    console.error("Error seeding books:", error);
  } finally {
    mongoose.connection.close();
  }
};

seedBooks();
